name: Docker Image
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  push:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image-push-to-ghcr.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
      version: 'latest'
      platform: 'linux/amd64'
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - app